version: '3.7'
services:
#  agent-1:
#    build: .
#    ports:
#     - "81:5000"
#  agent-2:
#    ports:
#     - "82:5000"
#  agent-3:
#    ports:
#     - "83:5000"
  blockchian_server:
    build: .
    image: blockchain
    ports:
      - 10000-10003:5000

#     abc:
       #    image: myimage
       #    command: abc
       #    build:
       #      context: .
       #      dockerfile: Dockerfile
       #
       #  xyz:
    #    image: myimage
    #    command: xyz