# docker-compose up --scale app=5
version: '3.7'
services:
#  agent-1:
#    build: .
#    ports:
#     - "81:5000"
#  agent-2:
#    ports:
#     - "82:5000"
#  agent-3:
#    ports:
#     - "83:5000"
  app:
    build: .
    ports:
      - 10000-10003:80

#     abc:
       #    image: myimage
       #    command: abc
       #    build:
       #      context: .
       #      dockerfile: Dockerfile
       #
       #  xyz:
    #    image: myimage
    #    command: xyz