version: '3.7'
services:
  blockchian_server:
    build: .
    image: blockchain
#    command: abc
    ports:
      - 10000-10003:5000 # (172.20.0.1:10000)
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
